allure-framework/allure-gradle

build.gradle
[//]: # (
.
.
)
[//]: # (
)
* downgrade java to 1.7
=> downgrade java to 1.7

build.gradle, src/main/groovy/io/qameta/allure/gradle/AllurePlugin.groovy, src/test/java/io/qameta/allure/gradle/DependenciesTest.java, src/test/java/io/qameta/allure/gradle/ReportTest.java, src/test/java/io/qameta/allure/gradle/TestNgSpiOffTest.java, src/test/java/io/qameta/allure/gradle/rule/GradleRunnerRule.java
=> fix gradle 3.5 compatibility (fixes #12)

src/it/spock/build.gradle, src/it/spock/src/test/groovy/tests/SpockTest.groovy, src/test/java/io/qameta/allure/gradle/DependenciesTest.java, src/test/java/io/qameta/allure/gradle/rule/GradleRunnerRule.java
=> add spock itest

README.md, build.gradle, src/it/junit5/build.gradle, src/it/junit5/src/test/java/tests/Junit5Test.java, src/it/junit5/src/test/resources/allure.properties, src/main/groovy/io/qameta/allure/gradle/AllureExtension.groovy, src/main/groovy/io/qameta/allure/gradle/AllurePlugin.groovy, src/main/groovy/io/qameta/allure/gradle/config/JUnit5Config.groovy, src/test/java/io/qameta/allure/gradle/DependenciesTest.java
=> junit5 support (fixes #17)

README.md, src/it/cucumber-jvm/build.gradle, src/it/junit4-autoconfigure/build.gradle, src/it/junit4/build.gradle, src/it/junit5/build.gradle, src/it/report-multi/build.gradle, src/it/report-task/build.gradle, src/it/spock/build.gradle, src/it/test-finalized-by-report/build.gradle, src/it/testng-autoconfigure/build.gradle, src/it/testng-spi-off/build.gradle, src/it/testng/build.gradle, src/main/groovy/io/qameta/allure/gradle/AllureExtension.groovy
=> update allure versions

src/it/categories/build.gradle, src/it/categories/build/allure-results/simple-result.json, src/it/categories/src/test/resources/categories.json, src/main/groovy/io/qameta/allure/gradle/task/AllureReport.groovy, src/main/groovy/io/qameta/allure/gradle/task/AllureServe.groovy, src/main/groovy/io/qameta/allure/gradle/util/BuildUtils.groovy, src/test/java/io/qameta/allure/gradle/CategoriesTest.java
=> copy categories from resources (fixes #21)

build.gradle, src/it/cucumber-jvm/build.gradle, src/it/junit4/build.gradle, src/it/junit5/build.gradle, src/it/spock/build.gradle, src/it/testng-spi-off/build.gradle, src/it/testng/build.gradle, src/main/groovy/io/qameta/allure/gradle/AllureExtension.groovy
=> update junit version

README.md, src/it/categories/build.gradle, src/it/cucumber-jvm/build.gradle, src/it/junit4-autoconfigure/build.gradle, src/it/junit4/build.gradle, src/it/junit5/build.gradle, src/it/report-multi/build.gradle, src/it/report-task/build.gradle, src/it/spock/build.gradle, src/it/test-finalized-by-report/build.gradle, src/it/testng-autoconfigure/build.gradle, src/it/testng-spi-off/build.gradle, src/it/testng/build.gradle, src/main/groovy/io/qameta/allure/gradle/AllureExtension.groovy
=> Versions update

README.md, src/it/cucumber2-jvm/build.gradle, src/it/cucumber2-jvm/src/test/java/tests/Cucumber2JvmTest.java, src/it/cucumber2-jvm/src/test/java/tests/Steps.java, src/it/cucumber2-jvm/src/test/resources/features/test.feature, src/main/groovy/io/qameta/allure/gradle/AllureExtension.groovy, src/main/groovy/io/qameta/allure/gradle/AllurePlugin.groovy, src/main/groovy/io/qameta/allure/gradle/config/Cucumber2JVMConfig.groovy, src/test/java/io/qameta/allure/gradle/DependenciesTest.java
[//]: # (
.
.
)
[//]: # (
)
Add support for cucumber2JVM configuration
=> Add support for cucumber 2.0+

src/main/groovy/io/qameta/allure/gradle/util/BuildUtils.groovy
=> Fix missing results directory

src/it/report-only/build.gradle, src/main/groovy/io/qameta/allure/gradle/util/BuildUtils.groovy
=> Fix missing sourceset

src/main/groovy/io/qameta/allure/gradle/AllureExtension.groovy
=> Update AspectJ version

.github/workflows/publish-release.yml
=> Fix release (disable gradle daemon)

allure-adapter-plugin/build.gradle.kts, allure-base-plugin/build.gradle.kts, allure-plugin/build.gradle.kts, allure-report-plugin/build.gradle.kts
=> Add plugin vcs

allure-adapter-plugin/src/main/kotlin/io/qameta/allure/gradle/adapter/AllureAdapterExtension.kt, allure-plugin/src/test/java/io/qameta/allure/gradle/allure/DependenciesTest.java, allure-plugin/src/test/java/io/qameta/allure/gradle/allure/TestNgSpiOffTest.java
=> Get rid test directory

allure-adapter-plugin/src/main/kotlin/io/qameta/allure/gradle/adapter/AllureAdapterExtension.kt, allure-base-plugin/src/main/kotlin/io/qameta/allure/gradle/base/tasks/AllureExecTask.kt, allure-plugin/src/test/kotlin/io/qameta/allure/gradle/report/TestAndAllureReportTest.kt, allure-report-plugin/src/main/kotlin/io/qameta/allure/gradle/report/tasks/AllureReport.kt, allure-report-plugin/src/main/kotlin/io/qameta/allure/gradle/report/tasks/AllureServe.kt
=> Fix allureReport --depends-on-tests and allureServe --depends-on-tests

allure-adapter-plugin/src/main/kotlin/io/qameta/allure/gradle/adapter/AllureAdapterExtension.kt
[//]: # (
)
This fixes Issue #85 
=> ensure projectVersion in executorInfo map is a  string

.github/workflows/build.yml, testkit-junit4/src/main/java/io/qameta/allure/gradle/rule/GradleRunnerRule.java
https://github.com/allure-framework/allure-gradle/pull/94
=> Reduce RAM pressure in GitHub Actions

allure-report-plugin/src/main/kotlin/io/qameta/allure/gradle/report/AllureReportExtension.kt, allure-report-plugin/src/main/kotlin/io/qameta/allure/gradle/report/tasks/AllureReport.kt
Add configuration to enable generating single file reports.
=> Add singleFile support

README.md
document singleFile (fixes #111)
[//]: # (
.
.
)
singleFile feature was not documented.
=> Document singleFile option
